# Generated by Django 2.1.4 on 2018-12-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=256)),
                ('phone_number', models.CharField(max_length=10)),
                ('automated_message', models.CharField(max_length=500)),
                ('positive_reply', models.CharField(max_length=500)),
                ('negative_reply', models.CharField(max_length=500)),
                ('follow_up', models.CharField(blank=True, default=None, max_length=500)),
                ('product_type', models.CharField(max_length=500)),
            ],
        ),
    ]
